version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pas123
      POSTGRES_DB: godb
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports: 
      - 3333:8080